version: '2.2'
services:
  nexus917999452711:
    image: budtmo/docker-android-x86-7.1.1
    container_name: c7999452711
    privileged: true
    scale: 1
    ports:
      - '7144:6080'
      - '2145:4723'
      - '4145:5554'
      - '8145:5555'
    volumes:
      - $PWD/example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - HTTPS_PROXY=http://45.146.131.164:3128
